language: php
php:
  - 5.5
  - 5.6
#  - hhvm-nightly

#matrix:
#  allow_failures:
#     - php: hhvm-nightly

addons:
  postgresql: "9.3"

sudo: false

install: 
   - composer install --dev
   - cp Tests/Fixtures/App/config/parameters.travis.yml Tests/Fixtures/App/config/parameters.yml
  
before_script:
  - psql -c 'create database test0;' -U postgres
  - php Tests/Fixtures/App/console --env=test cache:warmup
  - php Tests/Fixtures/App/console doctrine:schema:create --env=test --no-interaction
  - php Tests/Fixtures/App/console doctrine:fixtures:load --env=test --no-interaction

script: phpunit --coverage-text

notifications:
  email:
     - info@champs-libres.coop
